Repository jumpserver/docs, pull requests merged in 2024-05, with the labels that each got.

#631 feat: 对接小助手功能
  theme/main.html
Labels: 类型:新功能

#632 feat: 对接小助手功能
  theme/main.html
Labels: 类型:新功能

#633 feat: 对接小助手功能
  theme/main.html
Labels: 类型:新功能

#637 perf: 更新jmsctl
  docs/installation/jmsctl_sh.md
Labels: 类型:优化

#639 perf: 更新jmsctl
  docs/installation/jmsctl_sh.md
Labels: 类型:优化

#638 perf: 更新jmsctl
  docs/installation/jmsctl_sh.md
Labels: 类型:优化

#641 feat: Update v3.10.10
  docs/change_log.md
  mkdocs.yml
Labels: 类型:新功能

#643 feat: Update v3.10.10
  docs/change_log.md
  mkdocs.yml
Labels: 类型:新功能

#642 feat: Update v3.10.10
  docs/change_log.md
  mkdocs.yml
Labels: 类型:新功能

#646 fix: 数据库类型连接支持说明和云同步配图
  docs/guide/user/web_terminal.md
  docs/img/asset_list18.png
  docs/img/asset_list19.png
Labels: 🐛 Bug
