Repository jumpserver/docs, pull requests merged in 2024-04, with the labels that each got.

#605 perf: 删除学习班链接
  docs/css/extra.css
  theme/f2c-header.html
  theme/main.html
Labels: 类型:优化

#606 perf: 删除学习班链接
  docs/css/extra.css
  theme/f2c-header.html
  theme/main.html
Labels: 类型:优化

#607 perf: 删除学习班链接
  docs/css/extra.css
  theme/f2c-header.html
  theme/main.html
Labels: 类型:优化

#608 fix: winrm 图片替换
  docs/guide/system/remoteapp.md
  docs/img/remoteapp18.png
Labels: 类型:bug

#610 fix: winrm 图片替换
  docs/guide/system/remoteapp.md
  docs/img/remoteapp18.png
Labels: 类型:bug

#609 fix: winrm 图片替换
  docs/guide/system/remoteapp.md
  docs/img/remoteapp18.png
Labels: 类型:bug

#611 fix: 移动端导航栏空白区优化
  docs/css/extra.css
  theme/css/f2c-header.css
  theme/f2c-header.html
Labels: 类型:bug

#613 fix: 移动端导航栏空白区优化
  docs/css/extra.css
  theme/css/f2c-header.css
  theme/f2c-header.html
Labels: 类型:bug

#612 fix: 移动端导航栏空白区优化
  docs/css/extra.css
  theme/css/f2c-header.css
  theme/f2c-header.html
Labels: 类型:bug

#614 fix: 组件介绍和存储说明
  docs/architecture.md
  docs/guide/storages.md
Labels: 类型:bug

#616 fix: 组件介绍和存储说明
  docs/architecture.md
  docs/guide/storages.md
Labels: 类型:bug

#615 perf: 更新终端命令适配最新版本
  docs/architecture.md
  docs/dev/shell.md
  docs/guide/storages.md
Labels: 类型:bug

#620 feat: Update v3.10.8
  docs/change_log.md
  mkdocs.yml
Labels: 类型:新功能

#621 feat: Update v3.10.8
  docs/change_log.md
  mkdocs.yml
Labels: 类型:新功能

#622 perf: 文档内容优化
  docs/dev/shell.md
  docs/installation/setup_kubernetes/helm_online_install.md
  docs/installation/setup_linux_standalone/offline_install.md
  docs/installation/setup_linux_standalone/offline_upgrade.md
Labels: 类型:优化

#623 perf: 文档内容优化
  docs/dev/shell.md
  docs/installation/setup_kubernetes/helm_online_install.md
  docs/installation/setup_linux_standalone/offline_install.md
  docs/installation/setup_linux_standalone/offline_upgrade.md
Labels: 类型:优化

#624 perf: 文档内容优化
  docs/dev/shell.md
  docs/installation/setup_kubernetes/helm_online_install.md
  docs/installation/setup_linux_standalone/offline_install.md
  docs/installation/setup_linux_standalone/offline_upgrade.md
Labels: 类型:优化

#625 feat: 小助手测试
  theme/main.html
Labels: 类型:新功能

#627 feat: 小助手测试
  theme/main.html
Labels: 类型:新功能

#626 feat: 小助手测试
  theme/main.html
Labels: 类型:新功能

#628 feat: Update v3.10.9
  docs/change_log.md
  mkdocs.yml
Labels: 类型:新功能

#629 feat: Update v3.10.9
  docs/change_log.md
  mkdocs.yml
Labels: 类型:新功能

#630 feat: Update v3.10.9
  docs/change_log.md
  mkdocs.yml
Labels: 类型:新功能
