Repository jumpserver/docs, pull requests merged in 2024-03, with the labels that each got.

#586 perf: 更新虚拟应用demo
  docs/guide/system/remoteapp.md
  docs/img/remoteapp12.png
  docs/img/remoteapp13.png
  docs/img/remoteapp14.png
  docs/img/remoteapp15.png
  docs/img/remoteapp16.png
  docs/img/remoteapp17.png
Labels: 类型:优化

#588 perf: 更新虚拟应用demo
  docs/guide/system/remoteapp.md
  docs/img/remoteapp12.png
  docs/img/remoteapp13.png
  docs/img/remoteapp14.png
  docs/img/remoteapp15.png
  docs/img/remoteapp16.png
  docs/img/remoteapp17.png
Labels: 类型:优化

#587 perf: 更新虚拟应用demo
  docs/guide/system/remoteapp.md
  docs/img/remoteapp12.png
  docs/img/remoteapp13.png
  docs/img/remoteapp14.png
  docs/img/remoteapp15.png
  docs/img/remoteapp16.png
  docs/img/remoteapp17.png
Labels: 类型:优化

#589 perf: 更新学习班链接
  docs/dev/shell.md
  theme/f2c-header.html
Labels: 类型:优化

#591 perf: 更新学习班链接
  docs/dev/shell.md
  theme/f2c-header.html
Labels: 类型:优化

#590 perf: 更新学习班链接
  docs/dev/shell.md
  theme/f2c-header.html
Labels: 类型:优化

#592 feat: Update v3.10.6
  docs/change_log.md
  mkdocs.yml
Labels: 类型:新功能

#593 feat: Update v3.10.6
  docs/change_log.md
  mkdocs.yml
Labels: 类型:新功能

#594 feat: Update v3.10.6
  docs/change_log.md
  mkdocs.yml
Labels: 类型:新功能

#596 fix: 产品FAQ文档链接
  docs/faq/faq.md
  docs/installation/setup_linux_standalone/1panel_install.md
Labels: 类型:bug

#598 fix: 产品FAQ文档链接
  docs/faq/faq.md
  docs/installation/setup_linux_standalone/1panel_install.md
Labels: 类型:bug

#597 fix: 产品FAQ文档链接
  docs/faq/faq.md
  docs/installation/setup_linux_standalone/1panel_install.md
Labels: 类型:bug

#599 feat: Update v3.10.7
  docs/change_log.md
  mkdocs.yml
Labels: 类型:新功能

#600 feat: Update v3.10.7
  docs/change_log.md
  mkdocs.yml
Labels: 类型:新功能

#602 perf: 漏洞通知及修复方案
  docs/img/close_job.png
  docs/index.md
Labels: 类型:优化

#604 perf: 漏洞通知及修复方案
  docs/img/close_job.png
  docs/index.md
Labels: 类型:优化

#603 perf: 漏洞通知及修复方案
  docs/img/close_job.png
  docs/index.md
Labels: 类型:优化
